#!/usr/bin/expect
#log_user 0

set filename [ lindex $argv 0 ]
set user $env(USER)
set config /opt/gmail-cli/$user/config.sh
set now [ exec date +%s ]
set username [ exec head -1 $config ]
set password [ exec head -2 $config | tail -1 ]
set from [ exec head -3 $config | tail -1 ]

proc usage {} {
		puts "Usage:"
		puts "\t mailer"
		puts "\t\t or"
		puts "\t mailer <filename>"
		puts ""
		puts "The program sends emails from the CLI."
		puts "Use without arguments to compose emails using Vim. Saving and closing Vim will send the email."
		puts "Specify a filename as the argument to send mail from a file. This is the intended method to use from scripts."
		puts ""
		puts "Email file syntax (maintain the syntax with input file and with Vim)."
		puts "+------------------------------------------------------------------------------------+"
		puts "| Line      | Content                                                                |"
		puts "+------------------------------------------------------------------------------------+"
		puts "| 1         | Recipient email address(s). Seperate multiple addresses with spaces.   |" 
		puts "| 2         | Subject line. Begin the line with 'Subject: ' followed by the subject. |"
		puts "| 3 till EOF| Email message.                                                         |"
		puts "+------------------------------------------------------------------------------------+"
}

proc send_mail { u_name p_word f_addr a_list subj mail } {
		spawn openssl s_client -connect smtp.gmail.com:465 -crlf -ign_eof
		send "EHLO test\r"
		send "AUTH LOGIN\r"
		expect "334 VXNlcm5hbWU6" { send "$u_name\r" }
		expect "334 UGFzc3dvcmQ6" { send "$p_word\r" }
		expect "Accepted" { send "\r" }
		send "MAIL FROM: <$f_addr>\r"
		foreach addr $a_list {
				expect  "250*" { send "rcpt to: <$addr>\r"}
		}
		expect "250*" { send "DATA\r" }
		foreach addr $a_list {
				send "To: $addr\r"
		}
		expect "354*" { send "$subj\r" } 
		send "\r"
		send [ exec tail -n +3 $mail | sed {s/^\.$/<.>/g}]
		send "\r"
		send ".\r"
		send "quit\r"
}

if { $argc == 0 } {
		set to [ exec head -1 $filename ]
		set addr_list [ split $to ]
		set subject [ exec head -2 $filename | tail -1 ]
		send_mail $username $password $from $addr_list $subject $msg
} elseif { $filename == "-h" } {
		usage
} elseif { $filename == "--help" } {
		usage
} elseif { $argc > 1 } {
		puts "The program expects only one argument <filename>"
		usage 
} else {
		set msg "/tmp/mail-$now.txt"
		#log_user 1
		puts "Press ENTER to send mail"
		spawn vim $msg
		interact
		#log_user 0
		set to [ exec head -1 $msg ]
		set addr_list [ split $to ]
		set subject [ exec head -2 $msg | tail -1 ]
		send_mail $username $password $from $addr_list $subject $filename
}
		
